# Generated by Django 2.1.5 on 2019-02-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editor',
            name='email',
        ),
    ]
