# Generated by Django 2.1.5 on 2019-02-08 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_editor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
