# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-08 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_article_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_image',
        ),
    ]
