# Generated by Django 2.1.5 on 2019-02-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_editor_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editor',
            name='phone_number',
        ),
    ]
